repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-ast
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: requirements-txt-fixer
  - repo: https://github.com/hukkin/mdformat
    rev: 0.7.22 # Use the desired version
    hooks:
      - id: mdformat
      # Optionally add plugins for extended functionality, e.g., GitHub Flavored Markdown (GFM)
        additional_dependencies:
          - mdformat-gfm
          - mdformat-black # For black-style formatting within code blocks
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        language: system
        entry: uv run ruff check . --fix
        pass_filenames: false
        always_run: true
      - id: mypy
        name: mypy
        language: system
        entry: uv run mypy .
        pass_filenames: false
        always_run: true
      - id: pytest
        name: pytest
        language: system
        entry: uv run python -m pytest
        pass_filenames: false
        always_run: true
