[build-system]
requires = [
    "setuptools>=61.0",
]
build-backend = "setuptools.build_meta"

[project]
name = "denoisers"
version = "0.1.8"
authors = [
  { name="Will Rice", email="wrice20@gmail.com" },
]
description = "A package for training audio denoisers"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
]
dependencies = [
    "black>=24.10.0",
    "flake8-black>=0.3.6",
    "isort>=5.13.2",
    "mypy>=1.13.0",
    "pip-tools>=7.4.1",
    "pydocstyle>=6.3.0",
    "pytest>=8.3.3",
    "pytest-cov>=6.0.0",
    "pytorch-lightning>=2.4.0",
    "ruff>=0.7.4",
    "torch>=2.5.1",
    "torchaudio>=2.5.1",
    "torchvision>=0.20.1",
    "wandb>=0.18.7",
    "librosa>=0.10.2.post1",
    "matplotlib>=3.9.2",
    "pedalboard>=0.9.16",
    "transformers>=4.46.3",
    "pesq>=0.0.4",
    "audiomentations>=0.37.0",
    "pydub>=0.25.1",
    "pyroomacoustics>=0.8.2",
]

[project.urls]
"Homepage" = "https://github.com/will-rice/denoisers"
"Bug Tracker" = "https://github.com/will-rice/denoisers/issues"

[tool.isort]
known_first_party = ["denoisers"]

[tool.ruff]
ignore-init-module-imports = true

[tool.ruff.lint]
select = ["C", "E", "F", "I", "W", "D", "N", "B"]
ignore = ["D107"]

[tool.ruff.pydocstyle]
convention = "google"

[tool.pytest.ini_options]
filterwarnings = [
    "ignore::DeprecationWarning",
]

[tool.mypy]
ignore_missing_imports = true
follow_imports_for_stubs = true

[tool.uv.sources]
pesq = { git = "https://github.com/ludlows/PESQ.git" }

[project.scripts]
train = "denoisers.scripts.train:main"
publish = "denoisers.scripts.publish:main"
